"""
Natural language query endpoint — routes to the LangGraph agent.
"""

import hashlib
import time
import uuid

from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field

from app.agent.graph import build_agent_graph
from app.core.logging import get_logger

router = APIRouter()
log = get_logger(__name__)

# ── In-memory TTL cache (1-hour TTL, keyed on query+market) ──────────────────
_CACHE: dict[str, tuple[float, "QueryResponse"]] = {}
_CACHE_TTL = 3600  # seconds


def _cache_key(query: str, market_id: str) -> str:
    raw = f"{query.strip().lower()}|{market_id}"
    return hashlib.sha256(raw.encode()).hexdigest()[:20]


def _cache_get(key: str) -> "QueryResponse | None":
    entry = _CACHE.get(key)
    if entry and (time.time() - entry[0]) < _CACHE_TTL:
        return entry[1]
    if entry:
        del _CACHE[key]
    return None


def _cache_set(key: str, response: "QueryResponse") -> None:
    _CACHE[key] = (time.time(), response)


# ── Request / Response models ─────────────────────────────

class QueryRequest(BaseModel):
    query: str = Field(..., min_length=3, max_length=2000, description="Natural language question")
    market_id: str = Field(default="dc_metro", description="Market identifier (e.g. 'dc_metro', 'va')")
    session_id: str = Field(default_factory=lambda: str(uuid.uuid4()))

    class Config:
        json_schema_extra = {
            "example": {
                "query": "Compare MRI brain rates across Inova, HCA, and UVA",
                "market_id": "va",
            }
        }


class AgentMetadata(BaseModel):
    agent_nodes: list[str]
    execution_ms: int
    row_count: int
    state_filter: str
    sql: str | None = None


class QueryResponse(BaseModel):
    answer: str
    sql: str | None = None
    metadata: AgentMetadata


# ── State code mapping ─────────────────────────────────────

MARKET_TO_STATE: dict[str, str | None] = {
    "dc_metro": None,   # DC + MD + VA — no state filter, all networks visible
    "va":       "VA",
    "md":       "MD",
    "dc":       "DC",
    "nc":       "NC",
    "national": None,
}


# ── Routes ────────────────────────────────────────────────

@router.post("", response_model=QueryResponse)
async def query(request: QueryRequest) -> QueryResponse:
    """
    Submit a natural language query. The LangGraph agent will:
    1. Parse intent
    2. Map to procedure codes
    3. Generate SQL
    4. Execute against DuckDB
    5. Synthesize a natural language response
    """
    state_code = MARKET_TO_STATE.get(request.market_id, None)
    start_ms = int(time.time() * 1000)

    log.info("Query received", session=request.session_id, market=request.market_id,
             query_len=len(request.query))

    # ── Cache lookup ─────────────────────────────────────
    ck = _cache_key(request.query, request.market_id)
    cached = _cache_get(ck)
    if cached:
        log.info("Cache hit", session=request.session_id, key=ck)
        return cached

    try:
        agent = build_agent_graph()
        result = await agent.ainvoke({
            "user_query": request.query,
            "state_code": state_code,
            "session_id": request.session_id,
            "messages": [],
            "intent": None,
            "procedure_codes": [],
            "generated_sql": None,
            "query_results": None,
            "final_answer": None,
            "nodes_visited": [],
            "error": None,
        })
    except Exception as e:
        log.error("Agent execution failed", error=str(e), session=request.session_id)
        raise HTTPException(status_code=500, detail=f"Agent error: {e}")

    execution_ms = int(time.time() * 1000) - start_ms

    response = QueryResponse(
        answer=result.get("final_answer", "I was unable to generate a response."),
        sql=result.get("generated_sql"),
        metadata=AgentMetadata(
            agent_nodes=result.get("nodes_visited", []),
            execution_ms=execution_ms,
            row_count=len(result.get("query_results") or []),
            state_filter=state_code or "all",
            sql=result.get("generated_sql"),
        ),
    )

    # Only cache successful, non-empty responses
    if result.get("final_answer") and not result.get("error"):
        _cache_set(ck, response)

    return response


@router.post("/stream")
async def query_stream(request: QueryRequest) -> StreamingResponse:
    """
    Streaming version of the query endpoint using Server-Sent Events.
    Tokens are streamed as they are generated by the LLM.
    """
    state_code = MARKET_TO_STATE.get(request.market_id, "VA")

    async def event_generator():
        import json
        try:
            agent = build_agent_graph()
            async for event in agent.astream_events(
                {
                    "user_query": request.query,
                    "state_code": state_code,
                    "session_id": request.session_id,
                    "messages": [],
                    "intent": None,
                    "procedure_codes": [],
                    "generated_sql": None,
                    "query_results": None,
                    "final_answer": None,
                    "nodes_visited": [],
                    "error": None,
                },
                version="v2",
            ):
                if event["event"] == "on_chat_model_stream":
                    chunk = event["data"]["chunk"]
                    if hasattr(chunk, "content") and chunk.content:
                        payload = json.dumps({"type": "token", "content": chunk.content})
                        yield f"data: {payload}\n\n"
        except Exception as e:
            log.error("Stream error", error=str(e))
            yield f"data: {json.dumps({'type': 'error', 'message': str(e)})}\n\n"
        finally:
            yield "data: [DONE]\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
        },
    )
